### ISSUE TITLE
Delay when Stream from RTSP camera link

### ISSUE THREAD

**Issue by xxtkidxx** [dan246/VisionFlow#4]
Hi @dan246 
I have got delay about 1 second when using the RTSP link from a HIK camera
I tried both your OpenCV Code and FFMPEG Code on Worker Docker
How to reduce delay?
![image](https://github.com/user-attachments/assets/5e63c17b-417f-4447-a814-c36511e0fea0)

**Comment by dan246** [comment]
Hi @xxtkidxx ,

In the project, the FFmpeg decoding method is set to TCP by default:
`
ffmpeg_cmd = [
    'ffmpeg',
    '-rtsp_transport', 'tcp',
    '-loglevel', 'error',
    '-i', camera_url,
    '-vf', 'fps=1',
    '-f', 'rawvideo',
    '-pix_fmt', 'bgr24',  # Using 'bgr24' format
    'pipe:'
]
`
TCP is reliable but may introduce latency due to its acknowledgment and retransmission mechanisms. If real-time performance is a higher priority for your use case, switching to UDP as the transport protocol can help reduce the delay. 

P.S
You might be able to further reduce the delay by implementing the following mechanisms: lowering the FPS, adjusting the FPS buffer size, or using FFmpeg's low-latency mode, among others.

**Comment by xxtkidxx** [comment]
Hi @dan246 
Thanh you for response,
My camera (HIKVision) not suport UDP protocol. When I uncomment the lines '-rtsp_transport', 'tcp', error has occurred
When I use the config as shown in the photo, the delay is reduced to about 0.7s. Frame recognition delay is about 1s
It seems like it's the best result right now
![image](https://github.com/user-attachments/assets/bdb742cc-56b3-444b-97d4-d8cc5d0a2910)

**Comment by dan246** [comment]
Hi @xxtkidxx,

Thank you for your response and for sharing your findings. I understand your situation and the limitations with your camera. I will continue researching decoding techniques to further reduce latency. If I discover any new optimizations, I’ll make sure to update the project.

Likewise, if you make any progress or find a solution, please feel free to share it as well. 
Thank you!

**Comment by xxtkidxx** [comment]
Hi @dan246 
I am very interested in your project and willing to contribute my finding.
There is a problem of 300ms delay between stream and recognized stream when I use model Yolo11n.pt
I checked that the frame processing time on yolo is only 50ms
What is your opinion on this?
![image](https://github.com/user-attachments/assets/7c7b87f8-b085-488e-a734-e116d242380e)

**Comment by dan246** [comment]
Hi, @xxtkidxx
You're right; there's indeed no need to fetch camera_status from the API. This part has been fixed, and we can directly retrieve it from Redis. Also, I removed the supervision part—drawing the boxes directly using YOLO's results seems to be faster, doesn't it?

**Comment by xxtkidxx** [comment]
Hi @dan246 
I will try your new code and give feedback
Thank you for your efforts

**Comment by xxtkidxx** [comment]
I tried the new code, the time has improved and is more stable but is still at 0.2s
I have some questions
1.  My test system  with 4 cameras and 1 model, the total run for 1 loop take over 0.2s while the processing time of each camera is only 0.1s. Why is that?
![image](https://github.com/user-attachments/assets/610f8642-3678-4920-a18b-418e4cd9e90b)
2. Why is it necessary to set the waiting time for the next loop to at least 0.1s?
![image](https://github.com/user-attachments/assets/39344d44-eb45-4ca8-a8d9-0f6b0619b5e8)

**Comment by dan246** [comment]
Hi @xxtkidxx 

Thank you for your testing and feedback! This might be related to the overhead of asynchronous task switching or other logical factors. I’ve noted this issue and will analyze and optimize it further as soon as possible after I address my current tasks. If you have new observations or test results, feel free to share them with me!

**Comment by xxtkidxx** [comment]
Hi @dan246  
I hope new result from you
Thanks you

**Comment by dan246** [comment]
Hi @xxtkidxx,

**Based on your first question:**
The total runtime exceeds 0.2 seconds because cameras are processed sequentially, and model inference is a synchronous blocking operation. This prevents true parallel processing and causes delays.

By switching to batch processing, images from multiple cameras are fed into the model together, reducing repetitive overhead. This optimizes the workflow, bringing the total runtime closer to the duration of a single model inference while maintaining each camera’s processing time at 0.1 seconds.

**Based on your second question:**
Setting a minimum wait time of 0.1 seconds prevents the event loop from entering a busy-waiting state. Without it, the program might immediately start the next loop, overloading the CPU and causing instability.

This pause ensures system stability and efficiency. After optimizations like batch processing, you can fine-tune the wait time as needed, but care must be taken to avoid excessive resource use.

I hope this addresses your concerns! I’ve already pushed the test code to the dev branch as appv2.py. Let me know if you need further clarification or assistance!

**Comment by xxtkidxx** [comment]
Hi @dan246 
Cám ơn chia sẻ
![image](https://github.com/user-attachments/assets/2fe7dec7-9485-4780-8e88-bda5db7d2a51)
Thank you for your sharing, I tried  your code for 6 cameras,the recognition speed improved  but after about 1 minute it was frozen for 10 seconds then the stream worked normally again. I sent a photo of the log

**Comment by dan246** [comment]
Hi @xxtkidxx ,

Thank you for sharing the log and results. From the observation, it seems there might be a resource contention or busy-waiting issue during the batch processing, which could explain the freezing behavior and the -5.63 seconds log entry.

As a first step, I suggest adjusting the wait time between batches to see if it alleviates the problem. You can start with a small delay (e.g., 10ms or 50ms) after processing each batch. This might help reduce system contention and improve stability without significantly affecting performance.

Please let me know if this adjustment makes a difference. If not, we can dive deeper into analyzing resource usage or other potential bottlenecks.

**Comment by xxtkidxx** [comment]
Hi @dan246 
![image](https://github.com/user-attachments/assets/b803c07c-f066-49f5-8058-4a807ba386da)
The problem occurs while we fetch  images from Redis (i have been disabed detection fuction), I'm trying to do it the way you suggested. However, if possible, let's check together to get the best results

**Comment by dan246** [comment]
Thank you for your update. As a quick adjustment, I suggest modifying the `adjusted_sleep` calculation in your `main_loop` to ensure there is always at least a minimal sleep duration, even if the elapsed time is very short.

You can change:
```python
adjusted_sleep = max(0, self.SLEEP_INTERVAL - elapsed_time)
```

to:

```python
adjusted_sleep = max(0.001, self.SLEEP_INTERVAL - elapsed_time)
```

This ensures a minimum sleep time of 1 millisecond, which might help avoid busy-waiting and improve system stability. Please try this change and let me know if it makes any difference.

**Comment by xxtkidxx** [comment]
Hi @dan246 
I tried following your suggestion. The problem did not fix.
Please tell me your testing system? number of cameras, computer configuration and operating system. I will refer to it and check again
Thanks you

**Comment by dan246** [comment]
Hi @xxtkidxx 
OK, My testing system is configured as follows:

- **Operating System**: Windows 10  
- **GPU**: NVIDIA RTX 4090  
- **Number of Cameras**: 30  
- **Number of Workers**: 10  

This is the setup I used during testing, and I did not encounter any negative seconds issues under these conditions. Please refer to these specifications and check if there might be differences or limitations in your system setup. Let me know if you have further questions or need additional support.

**Comment by dan246** [comment]
@xxtkidxx 

Thank you for your question. Initially, I set the FPS to 30 for testing the system under a realistic workload with all 30 cameras running at high frame rates. However, during debugging and issue analysis, I later reduced the FPS to 1.

This adjustment was made for the following reasons:
1. **Lowering system load**: At 30 FPS, the total workload (especially for 30 cameras) was very high, which could make it difficult to isolate bottlenecks in the system.
2. **More controlled environment**: By reducing the FPS to 1, the data processing became more stable and manageable, making it easier to analyze specific issues like Redis operations or async scheduling.
3. **Simplified debugging**: With lower frame rates, I was able to pinpoint issues more effectively without being overwhelmed by the high volume of data.

**Comment by dan246** [comment]
@xxtkidxx 
Thank you for the suggestion! I’ve already switched to using time.monotonic() in the dev branch. Regarding the new issue, I recommend starting with Gunicorn for better performance. Here are the details:
**Install Gunicorn**
You can install Gunicorn using pip:

`pip install gunicorn
`

**Run Flask with Gunicorn**

Replace the Flask development server with Gunicorn for production use. Use the following command:

`gunicorn -w 4 -k gevent -b 0.0.0.0:5000 --timeout 120 app:app`

Options explained:

- `-w 4`: Specifies the number of worker processes. Adjust this based on your server's CPU cores.
- `-k gevent`: Enables asynchronous workers, allowing efficient handling of multiple requests simultaneously.
- `--timeout 120`: Prevents Gunicorn from prematurely killing long-running requests.

**Optimize Your Code (Still to be Tested)**

Replace time.sleep with await asyncio.sleep to ensure non-blocking execution. This is especially important for routes like /recognized_stream/<camera_id>.

These steps should improve your application's performance and help prevent the server from getting stuck when handling a high volume of requests. Let me know if you need further assistance!
